export { handleChangeEmail } from './handleChangeEmail';
export { handleChangePhone } from './handleChangePhone';
export { handleCheckAuth } from './handleCheckAuth';
export { handleLogin } from './handleLogin';
export { handleLogout } from './handleLogout';
export { handleRequestPasswordRecovery } from './handleRequestPasswordRecovery';
export { handleResendEmailConfirmation } from './handleResendEmailConfirmation';
export { handleSetNewPassword } from './handleSetNewPassword';
export { handleSignup } from './handleSignup';
